#[target.aarch64-linux-android]
#linker = "E:/work/android-ndk-r29/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang.cmd"

#[env]
#CC_aarch64-linux-android = "E:/work/android-ndk-r29/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang.cmd"
#CXX_aarch64-linux-android = "E:/work/android-ndk-r29/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android26-clang++.cmd"
#AR_aarch64-linux-android = "E:/work/android-ndk-r29/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"

[target.aarch64-linux-android]
linker = "/home/loyetu/work/tools/android-ndk-r29/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"

[env]
CC_aarch64_linux_android = "/home/loyetu/work/tools/android-ndk-r29/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"
CXX_aarch64_linux_android = "/home/loyetu/work/tools/android-ndk-r29/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang++"
AR_aarch64_linux_android = "/home/loyetu/work/tools/android-ndk-r29/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"