// src/sensor/snapshot_writer.rs
//
// 任务 #5 / ticket-09: 200ms tick 把 SenseSnapshot 序列化为 yaml 文件,
// 供 WebUI 通过 KSU exec cat 读取, 驱动首页/感知实时刷新.
//
// 输出路径 (双写):
//   - <MODULE_ROOT>/sense/snapshot.yaml          (老路径, 兼容)
//   - <MODULE_ROOT>/webroot/sense/snapshot.yaml  (WebView http 相对路径兜底)
//
// 字段对齐 webui/src/api/sense.ts::SenseSnapshot 接口 (前端定义的字段顺序 = 本文件输出顺序).
// 字段值缺失 (采集器崩 / 文件不可读) 时用 safe-default (0 / false / 0.0).

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::thread;
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use log::{debug, info, warn};

use crate::monitor::sense_snapshot::{sense_now, SenseSnapshot};
use crate::common::get_module_root;

/// Sense snapshot tick 周期 = 与 hotplug 一致 200ms (5Hz)
const SENSE_TICK_MS: u64 = 200;
/// 写盘防抖间隔: 200ms tick 内只写 1 次 (避免 eMMC 抖动)
const WRITE_INTERVAL_MS: u64 = 200;
/// SoC 温度采样间隔 (thermal_zone 读文件不便宜, 1s 足够)
const TEMP_SAMPLE_MS: u64 = 1000;
/// 屏幕刷新率轮询间隔 (dumpsys display 是子进程调用, 不能太频繁)
const HZ_POLL_MS: u64 = 2000;

fn sense_dir() -> PathBuf {
    get_module_root().join("sense")
}

fn webroot_sense_dir() -> PathBuf {
    get_module_root().join("webroot").join("sense")
}

fn snapshot_paths() -> Vec<PathBuf> {
    vec![sense_dir().join("snapshot.yaml"), webroot_sense_dir().join("snapshot.yaml")]
}

const INIT_BODY: &str = "# Auto-generated by core-pilot sensor loop. Do not edit.\n\
     cpu_utils_pct: [0,0,0,0,0,0,0,0]\n\
     gpu_load_pct: 0\n\
     io_some_pct: 0\n\
     io_full_pct: 0\n\
     mem_full_pct: 0\n\
     mem_full_us: 0\n\
     swap_used_mb: 0\n\
     temp_c: 0.0\n\
     fps: 0\n\
     display_hz: 0\n\
     screen_on: false\n\
     touch_down: false\n\
     touch_age_ms: 9999\n\
     current_pkg: \"\"\n\
     updated_at_unix_ms: 0\n";

/// customize.sh 启动时调用: 创建空 snapshot.yaml (避免 WebUI 第一次读报错)
pub fn init_sense_state_file() -> Result<()> {
    for dir in [sense_dir(), webroot_sense_dir()] {
        fs::create_dir_all(&dir).with_context(|| format!("mkdir {}", dir.display()))?;
        let path = dir.join("snapshot.yaml");
        if !Path::new(&path).exists() {
            let mut f = fs::File::create(&path)?;
            f.write_all(INIT_BODY.as_bytes())?;
        }
    }
    Ok(())
}

/// 后台线程: 每 HZ_POLL_MS 读一次屏幕当前刷新率并 push 进 sense 快照.
///
/// 数据源 `dumpsys display` 的 renderFrameRate (= 当前激活模式的 Hz,
/// 本机支持 30/40/60/90/120). 用户说的"屏幕刷新率"就是这个值;
/// fps (uprobe 实测出帧速率) 是另一个概念, 两个字段分开.
fn start_hz_poller() {
    thread::Builder::new()
        .name("hz_poller".to_string())
        .spawn(|| loop {
            let hz = read_display_hz();
            crate::monitor::sense_snapshot::hz_push(hz);
            thread::sleep(Duration::from_millis(HZ_POLL_MS));
        })
        .ok();
}

/// dumpsys display | 第一个 renderFrameRate 数值; 失败 → 0.0
fn read_display_hz() -> f32 {
    let out = match Command::new("dumpsys").arg("display").output() {
        Ok(o) => o.stdout,
        Err(_) => return 0.0,
    };
    let text = String::from_utf8_lossy(&out);
    for line in text.lines() {
        if let Some(idx) = line.find("renderFrameRate") {
            let rest = &line[idx + "renderFrameRate".len()..];
            let num: String = rest
                .trim_start()
                .chars()
                .take_while(|c| c.is_ascii_digit() || *c == '.')
                .collect();
            if let Ok(v) = num.parse::<f32>() {
                if v > 20.0 && v < 500.0 {
                    return v;
                }
            }
        }
    }
    0.0
}

/// 启动 sensor snapshot 写盘线程 (独立线程, 200ms tick)
pub fn start_sense_snapshot_thread() -> Result<()> {
    init_sense_state_file()?;
    start_hz_poller();

    thread::Builder::new()
        .name("sense_snapshot".to_string())
        .spawn(|| {
            info!("sense snapshot loop started");
            let mut last_write: Option<Instant> = None;
            let mut last_temp_sample: Option<Instant> = None;
            // 任务 #6 reliability: 200ms tick 是稳定的兜底心跳源. 即便
            // app_detect 线程或 scheduler_ipc 线程都卡住, snapshot_writer
            // 仍在每 200ms 写一次文件, watchdog 不会超时.
            crate::watchdog::heartbeat_tick();
            loop {
                crate::watchdog::heartbeat_tick();
                let start = Instant::now();
                let snap = sense_now();

                // Ticket: 温度采集 — 此前 temp_push never used, snapshot.yaml 的
                // temp_c 恒 0. 复用 hotplug 同源 thermal zone (utils::find_cpu_temp_path).
                let need_temp = last_temp_sample
                    .map_or(true, |t| start.duration_since(t) >= Duration::from_millis(TEMP_SAMPLE_MS));
                if need_temp {
                    last_temp_sample = Some(start);
                    let millic = read_soc_temp_millic();
                    if millic != 0 {
                        crate::monitor::sense_snapshot::temp_push(millic);
                    }
                }

                let should_write = last_write.map_or(true, |t| start.duration_since(t) >= Duration::from_millis(WRITE_INTERVAL_MS));
                if should_write {
                    if let Err(e) = write_snapshot_yaml(&snap) {
                        warn!("sense: write snapshot.yaml failed: {}", e);
                    }
                    last_write = Some(start);
                }

                let elapsed = start.elapsed();
                if elapsed < Duration::from_millis(SENSE_TICK_MS) {
                    thread::sleep(Duration::from_millis(SENSE_TICK_MS) - elapsed);
                }
            }
        })?;
    Ok(())
}

/// hotplug 同源: thermal zone millidegree; 找不到路径 → 0
fn read_soc_temp_millic() -> i32 {
    let path = match crate::utils::find_cpu_temp_path() {
        Ok(p) if !p.is_empty() => p,
        _ => return 0,
    };
    match crate::utils::read_f64_from_file(&path) {
        Ok(raw) => raw as i32,
        Err(_) => 0,
    }
}

fn write_snapshot_yaml(snap: &SenseSnapshot) -> Result<()> {
    let mut cpu_utils = vec![0.0_f32; 8];
    for (i, e) in snap.cpu.cpus.iter().enumerate().take(8) {
        cpu_utils[i] = e.util_pct;
    }
    let cpu_utils_str = cpu_utils
        .iter()
        .map(|v| format!("{:.1}", v))
        .collect::<Vec<_>>()
        .join(",");

    let gpu_load = if snap.gpu.load_pct.is_nan() { 0.0 } else { snap.gpu.load_pct };
    let mem_full_us = snap.swap.mem_full_us;
    let swap_used_mb = snap.swap.zram_used_bytes / (1024 * 1024);

    // Bugfix: 此前读环境变量 CORE_PILOT_CURRENT_PKG (daemon 进程 env 恒空).
    // app_detect 线程已经在维护 CURRENT_PACKAGE, 直接读它.
    let pkg = crate::monitor::app_detect::current_package();

    // Bugfix: mem_full_pct 此前 = PSI total(us)/10000 → 恒 clamp 到 100.
    // avg10 才是 PSI 原生百分比.
    let mem_full_pct = snap.swap.mem_full_avg10_pct.clamp(0.0, 100.0);

    let temp_c = snap.temp_c();
    let display_hz = snap.display_hz;

    let now_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);

    let body = format!(
        "# Auto-generated by core-pilot sensor loop. Do not edit.\n\
         cpu_utils_pct: [{cpu_utils_str}]\n\
         gpu_load_pct: {gpu_load:.1}\n\
         io_some_pct: {io_some:.1}\n\
         io_full_pct: {io_full:.1}\n\
         mem_full_pct: {mem_full_pct:.1}\n\
         mem_full_us: {mem_full_us}\n\
         swap_used_mb: {swap_used_mb}\n\
         temp_c: {temp_c:.1}\n\
         fps: {fps}\n\
         display_hz: {display_hz:.1}\n\
         screen_on: {screen_on}\n\
         touch_down: {touch_down}\n\
         touch_age_ms: {touch_age}\n\
         current_pkg: \"{pkg}\"\n\
         updated_at_unix_ms: {now_ms}\n",
        cpu_utils_str = cpu_utils_str,
        gpu_load = gpu_load,
        io_some = snap.io.some_pct,
        io_full = snap.io.full_pct,
        mem_full_pct = mem_full_pct,
        mem_full_us = mem_full_us,
        swap_used_mb = swap_used_mb,
        temp_c = temp_c,
        fps = snap.fps,
        display_hz = display_hz,
        screen_on = snap.screen_on,
        touch_down = snap.touch.down,
        touch_age = snap.touch.last_event_age_ms,
        pkg = escape_yaml_str(&pkg),
        now_ms = now_ms,
    );

    // 双写: 老 sense/ 路径 (兼容) + webroot/sense/ (WebView http 相对 fetch 兜底)
    let mut last_err = None;
    for path in snapshot_paths() {
        let tmp_path = path.with_extension("yaml.tmp");
        let write = || -> Result<()> {
            {
                let mut f = fs::File::create(&tmp_path)
                    .with_context(|| format!("create tmp {}", tmp_path.display()))?;
                f.write_all(body.as_bytes())?;
                f.sync_all().ok();
            }
            fs::rename(&tmp_path, &path)
                .with_context(|| format!("rename {} -> {}", tmp_path.display(), path.display()))
        };
        if let Err(e) = write() {
            warn!("sense: write {} failed: {}", path.display(), e);
            last_err = Some(e);
        }
    }
    if let Some(e) = last_err {
        return Err(e);
    }
    debug!("sense: wrote snapshot.yaml ({} bytes, dual-path)", body.len());
    Ok(())
}

fn escape_yaml_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escape_handles_quotes_and_backslashes() {
        assert_eq!(escape_yaml_str(""), "");
        assert_eq!(escape_yaml_str("com.x"), "com.x");
        assert_eq!(escape_yaml_str("a\"b"), "a\\\"b");
        assert_eq!(escape_yaml_str("a\\b"), "a\\\\b");
    }

    #[test]
    fn mem_full_pct_uses_psi_avg10_not_total() {
        use crate::monitor::sense_snapshot::SwapState;
        // total 累计 us 再大也不该影响 pct — avg10 才是百分比
        let mut snap = SenseSnapshot::default();
        snap.swap = SwapState {
            mem_full_us: 100_000_000,
            mem_full_avg10_pct: 37.5,
            ..Default::default()
        };
        let body_needed = snap.swap.mem_full_avg10_pct.clamp(0.0, 100.0);
        assert!((body_needed - 37.5).abs() < 0.01, "got {}", body_needed);
    }
}