// src/sensor/snapshot_writer.rs
//
// 任务 #5 / ticket-09: 200ms tick 把 SenseSnapshot 序列化为 yaml 文件,
// 供 WebUI 通过 KSU exec cat 读取, 驱动 SensePanel 实时刷新.
//
// 输出路径: <MODULE_ROOT>/sense/snapshot.yaml
//
// 字段对齐 webui/src/api/sense.ts::SenseSnapshot 接口 (前端定义的字段顺序 = 本文件输出顺序).
// 字段值缺失 (采集器崩 / 文件不可读) 时用 safe-default (0 / false / 0.0).

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::thread;
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use log::{debug, info, warn};

use crate::monitor::sense_snapshot::{sense_now, SenseSnapshot};
use crate::common::get_module_root;

/// Sense snapshot tick 周期 = 与 hotplug 一致 200ms (5Hz)
const SENSE_TICK_MS: u64 = 200;
/// 写盘防抖间隔: 200ms tick 内只写 1 次 (避免 eMMC 抖动)
const WRITE_INTERVAL_MS: u64 = 200;

fn sense_dir() -> PathBuf {
    get_module_root().join("sense")
}

fn snapshot_path() -> PathBuf {
    sense_dir().join("snapshot.yaml")
}

/// customize.sh 启动时调用: 创建空 snapshot.yaml (避免 WebUI 第一次读报错)
pub fn init_sense_state_file() -> Result<()> {
    let dir = sense_dir();
    fs::create_dir_all(&dir).with_context(|| format!("mkdir {}", dir.display()))?;

    let path = snapshot_path();
    if !Path::new(&path).exists() {
        let body = "# Auto-generated by core-pilot sensor loop. Do not edit.\n\
                     cpu_utils_pct: [0,0,0,0,0,0,0,0]\n\
                     gpu_load_pct: 0\n\
                     io_some_pct: 0\n\
                     io_full_pct: 0\n\
                     mem_full_pct: 0\n\
                     mem_full_us: 0\n\
                     swap_used_mb: 0\n\
                     temp_c: 0.0\n\
                     fps: 0\n\
                     screen_on: false\n\
                     touch_down: false\n\
                     touch_age_ms: 9999\n\
                     current_pkg: \"\"\n\
                     updated_at_unix_ms: 0\n";
        let mut f = fs::File::create(&path)?;
        f.write_all(body.as_bytes())?;
    }
    Ok(())
}

/// 启动 sensor snapshot 写盘线程 (独立线程, 200ms tick)
pub fn start_sense_snapshot_thread() -> Result<()> {
    init_sense_state_file()?;

    thread::Builder::new()
        .name("sense_snapshot".to_string())
        .spawn(|| {
            info!("sense snapshot loop started");
            let mut last_write: Option<Instant> = None;
            // 任务 #6 reliability: 200ms tick 是稳定的兜底心跳源. 即便
            // app_detect 线程或 scheduler_ipc 线程都卡住, snapshot_writer
            // 仍在每 200ms 写一次文件, watchdog 不会超时.
            crate::watchdog::heartbeat_tick();
            loop {
                crate::watchdog::heartbeat_tick();
                let start = Instant::now();
                let snap = sense_now();

                let should_write = last_write.map_or(true, |t| start.duration_since(t) >= Duration::from_millis(WRITE_INTERVAL_MS));
                if should_write {
                    if let Err(e) = write_snapshot_yaml(&snap) {
                        warn!("sense: write snapshot.yaml failed: {}", e);
                    }
                    last_write = Some(start);
                }

                let elapsed = start.elapsed();
                if elapsed < Duration::from_millis(SENSE_TICK_MS) {
                    thread::sleep(Duration::from_millis(SENSE_TICK_MS) - elapsed);
                }
            }
        })?;
    Ok(())
}

fn write_snapshot_yaml(snap: &SenseSnapshot) -> Result<()> {
    let mut cpu_utils = vec![0.0_f32; 8];
    for (i, e) in snap.cpu.cpus.iter().enumerate().take(8) {
        cpu_utils[i] = e.util_pct;
    }
    let cpu_utils_str = cpu_utils
        .iter()
        .map(|v| format!("{:.1}", v))
        .collect::<Vec<_>>()
        .join(",");

    let temp_c = snap.temp_c();
    let mem_full_pct = compute_mem_full_pct(snap);
    let swap_used_mb = snap.swap.zram_used_bytes / (1024 * 1024);

    // pkg 从环境变量取; 实际项目里 app_detect 会把 pkg 推到 OnceLock<String>.
    // 任务 #5 当前: 先走环境变量 fallback, 后续在 ticket-09 后续补 OnceLock 注入.
    let pkg = std::env::var("CORE_PILOT_CURRENT_PKG").unwrap_or_default();

    let now_ms = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);

    let body = format!(
        "# Auto-generated by core-pilot sensor loop. Do not edit.\n\
         cpu_utils_pct: [{cpu_utils_str}]\n\
         gpu_load_pct: {gpu_load:.1}\n\
         io_some_pct: {io_some:.1}\n\
         io_full_pct: {io_full:.1}\n\
         mem_full_pct: {mem_full_pct:.1}\n\
         mem_full_us: {mem_full_us}\n\
         swap_used_mb: {swap_used_mb}\n\
         temp_c: {temp_c:.1}\n\
         fps: {fps}\n\
         screen_on: {screen_on}\n\
         touch_down: {touch_down}\n\
         touch_age_ms: {touch_age}\n\
         current_pkg: \"{pkg}\"\n\
         updated_at_unix_ms: {now_ms}\n",
        cpu_utils_str = cpu_utils_str,
        gpu_load = snap.gpu.load_pct,
        io_some = snap.io.some_pct,
        io_full = snap.io.full_pct,
        mem_full_pct = mem_full_pct,
        mem_full_us = snap.swap.mem_full_us,
        swap_used_mb = swap_used_mb,
        temp_c = temp_c,
        fps = snap.fps,
        screen_on = snap.screen_on,
        touch_down = snap.touch.down,
        touch_age = snap.touch.last_event_age_ms,
        pkg = escape_yaml_str(&pkg),
        now_ms = now_ms,
    );

    let path = snapshot_path();
    let tmp_path = path.with_extension("yaml.tmp");
    {
        let mut f = fs::File::create(&tmp_path)
            .with_context(|| format!("create tmp {}", tmp_path.display()))?;
        f.write_all(body.as_bytes())?;
        f.sync_all().ok();
    }
    fs::rename(&tmp_path, &path)
        .with_context(|| format!("rename {} -> {}", tmp_path.display(), path.display()))?;
    debug!("sense: wrote snapshot.yaml ({} bytes)", body.len());
    Ok(())
}

fn compute_mem_full_pct(snap: &SenseSnapshot) -> f32 {
    // /proc/pressure/memory full=10 时间窗是 10ms = 10_000us
    // 公式: pct = (mem_full_us / 10_000) * 100, 然后 clamp 0..100
    // 任务 #4 review: 原版 / 10_000_000.0 * 100.0 多一万倍, 此处按正确公式修.
    let pct = (snap.swap.mem_full_us as f32) / 10_000.0 * 100.0;
    pct.clamp(0.0, 100.0)
}

fn escape_yaml_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escape_handles_quotes_and_backslashes() {
        assert_eq!(escape_yaml_str(""), "");
        assert_eq!(escape_yaml_str("com.x"), "com.x");
        assert_eq!(escape_yaml_str("a\"b"), "a\\\"b");
        assert_eq!(escape_yaml_str("a\\b"), "a\\\\b");
    }

    #[test]
    fn mem_full_pct_clamps_extreme() {
        use crate::monitor::sense_snapshot::SwapState;
        let mut snap = SenseSnapshot::default();
        snap.swap = SwapState { mem_full_us: 100_000_000, ..Default::default() };
        let pct = compute_mem_full_pct(&snap);
        assert!((pct - 100.0).abs() < 0.01, "got {}", pct);

        snap.swap.mem_full_us = 0;
        let pct = compute_mem_full_pct(&snap);
        assert_eq!(pct, 0.0);

        snap.swap.mem_full_us = 1000;
        let pct = compute_mem_full_pct(&snap);
        assert!((pct - 10.0).abs() < 0.01);
    }
}